Add annotation back for debug

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,9 +20,14 @@ jobs:
         run: brew install ldid dpkg 2>&1 || true
 
       - name: Build Package
-        run: make package
+        run: |
+          make package 2>&1 | tee /tmp/build.log; rc=${PIPESTATUS[0]}
+          logs=$(tail -30 /tmp/build.log | perl -pe 's/\n/%0A/g' | perl -pe "s/'/''/g")
+          echo "::error title=Build Error::exit $rc%0A$logs"
+          exit $rc
 
       - name: Upload .deb
+        if: success()
         uses: actions/upload-artifact@v4
         with:
           name: deb-package
